### ISSUE TITLE
Dockerhub image

### ISSUE THREAD

**Issue by jakeaston** [griddb/nodejs_client#17]
Would it be possible to push a nodes Docker client  image similar to your Python client to DockerHub?

I’m struggling to compile this in to a docket image on Mac OS.

**Comment by knonomura** [comment]
Thank you for your usage.
I understand.
GridDB team will push docker image for Node.JS Client similar to Python Client to DockerHub.

**Comment by knonomura** [comment]
We have created the image and pushed it into docker hub: https://hub.docker.com/repository/docker/griddbnet/griddb-nodejs

It can be pulled with the following command: 
<pre>
docker pull griddbnet/griddb-nodejs
</pre>

And could you please refer to our comment in
https://old.reddit.com/r/node/comments/eu6q0p/docker_image_of_griddb_nodejs_client/ ?

**Comment by jakeaston** [comment]
Thank you for putting some time into this.

For some reason I'm getting this error when running or building for scratch:

`/opt/nodejs/node_modules/griddb_node/lib/griddb_node.js:42
            throw(convertToGSException(err));
            ^`

Not sure if this is a network issue or something from the library. Any ideas?

**Comment by Imisrael** [comment]
That error occurs because the nodejs container can't find a server to connect to. The current docker images for the different language plugins are simply vessels to run applications; the nodejs image, as it exists on dockerhub, expects that you are also running a griddb server container. The nodejs container attempts to connect to a griddb-server and then run some sample code as a way of ensuring it's working. Once confirmed working, we anticipate that you will write new nodejs code and replace it with the sample code in your docker file. 

You can understand this workflow by reading this blog (and maybe watching the video): https://griddb.net/en/blog/improve-your-devops-with-griddb-server-and-client-docker-containers/

This is what the docker image on dockerhub looks like:

```
FROM node:10

RUN wget https://github.com/griddb/c_client/releases/download/v4.3.0/griddb-c-client_4.3.0_amd64.deb
RUN dpkg -i griddb-c-client_4.3.0_amd64.deb

WORKDIR /opt/nodejs
COPY package*.json ./
RUN npm install

ENV LD_LIBRARY_PATH /usr/griddb_c_client-4.3.0/lib/

ADD blogSample.js /opt/nodejs
CMD ["node", "/opt/nodejs/blogSample.js"]
```

As you can see, you simply need to replace the blogSample.js with your own nodejs code. 

Also, this is how you enter in the griddb-server container's credentials (in nodejs)

```
const factory = griddb.StoreFactory.getInstance();
const store = factory.getStore({
    "notificationMember": "griddb-server:10001",
    "clusterName": "defaultCluster",
    "username": "admin",
    "password": "admin"
});
```

**Comment by jakeaston** [comment]
Sorted. 

I had entered the Gateway IP instead of the access point IP of the griddb-server container.

Many thanks, Your help is much appreciated!
